# Generated by Django 3.0.7 on 2020-06-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='_body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='_title',
        ),
    ]
