# Generated by Django 3.0.7 on 2020-06-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200618_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_body',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_title',
        ),
    ]
